---
title: "names and pop culture"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r}
library(tidyverse)
```
```{r}
library(babynames)

```


```{r}
babynames %>%
  #filter(name %in% c("Madison", "Hermione", "Chandler", "Cady", "Barack", "Diana", "Heather", "Elle", "Ariel")) %>%
  filter(name %in% c("Ariel", "Madison", "Arielle"), sex=="F") %>%
  filter(year>=1975) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = name))
```

```{r}
babynames %>%
  #filter(name %in% c("Madison", "Hermione", "Chandler", "Cady", "Barack", "Diana", "Heather", "Elle", "Ariel")) %>%
  filter(name %in% c("Chandler", "Monica", "Ross", "Rachel", "Phoebe", "Joey")) %>%
  filter(year>=1980) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y")
```
```{r}
babynames %>%
  #filter(name %in% c("Madison", "Hermione", "Chandler", "Cady", "Barack", "Diana", "Heather", "Elle", "Ariel")) %>%
  filter(name %in% c("Cher", "Dionne"), sex=="F") %>%
  filter(year>=1960) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = name)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = 1995), linetype = "dashed", color = "red")
```

```{r}
babynames %>%
  #filter(name %in% c("Madison", "Hermione", "Chandler", "Cady", "Barack", "Diana", "Heather", "Elle", "Ariel")) %>%
  filter(name %in% c("Jerry", "Elaine")) %>%
  filter(year>=1980) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y")
```



```{r}
princess_names <- c("Ariel", "Belle", "Jasmine", "Mulan", "Tiana", "Merida", "Elsa", "Giselle")



princess_yrs <- data.frame(
  name = princess_names, 
  
  year = c(1989, 1991, 1992, 1998, 2009, 2012, 2013, 2007)
  
  
)


babynames %>%
  filter(name %in% princess_names, sex == "F") %>%
  filter(year>=1980) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = name)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = year),
             linetype="dashed",
             color = "red",
             data = princess_yrs)
  
```
```{r}
prince_names <- c("Eric", "Adam", "Aladdin", "Shang", "Naveen", "Kristoff", "Flynn") 

prince_yrs <- data.frame(
  name = prince_names, 
  
  year = c(1989, 1991, 1992, 1998, 2009, 2013, 2010)
  
  
)

babynames %>%
  filter(name %in% prince_names, sex == "M") %>%
  filter(year>=1980) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = name)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = year),
             linetype="dashed",
             color = "red",
             data = prince_yrs)
```


```{r}
babynames %>%
  #filter(name %in% c("Madison", "Hermione", "Chandler", "Cady", "Barack", "Diana", "Heather", "Elle", "Ariel")) %>%
  filter(name %in% c("Percy", "Annabeth", "Grover")) %>%
  filter(year>=1990) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = name)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = 2005),
             linetype = "dashed",
             color = "red")
```

```{r}

#year markers, introduction for Harry, ron, hermione, luna, minerva, and bellatrix. increasd involvement for ginny and neville, when he became good for severus


hp_names <- c("Harry", "Ron", "Hermione", "Neville", "Ginny", "Luna", "Minerva", "Bellatrix", "Severus", "Sirius", "Draco")

book_dates <- data.frame(
  name=hp_names, year = c(1997, 1997, 1997, 1997, 2003, 2003, 1997, 2003, 2007, 1999, 1997)
)

movie_dates <- data.frame(
  name=hp_names, year = c(2001, 2001, 2001, 2001, 2007, 2007, 2001, 2007, 2011, 2004, 2001)
)

babynames %>%
  #filter(name %in% c("Madison", "Hermione", "Chandler", "Cady", "Barack", "Diana", "Heather", "Elle", "Ariel")) %>%
  filter(name %in% hp_names) %>%
  filter(year>=1990) %>%
  ggplot() +
  geom_point(mapping = aes( x = year, y = n, color = name)) + 
   geom_vline(aes(xintercept = year),
             linetype="dashed",
             color = "red",
             data = book_dates) +
   geom_vline(aes(xintercept = year),
             linetype="dashed",
             color = "navy",
             data = movie_dates) +
  facet_wrap(~name, scales = "free_y")
  

  

```


 

```{r}
babynames %>%
  #filter(name %in% c("Madison", "Hermione", "Chandler", "Cady", "Barack", "Diana", "Heather", "Elle", "Ariel")) %>%
  filter(name %in% c("Edward", "Esme", "Carlisle", "Emmett", "Alice", "Rosalie", "Jasper", "Bella")) %>%
  filter(year>=2000) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y") +  
  geom_vline(aes(xintercept = 2005),
             linetype = "dashed",
             color = "red") + 
    geom_vline(aes(xintercept = 2008),
             linetype = "dashed",
             color = "navy")
```
```{r}
babynames %>%
  #filter(name %in% c("Madison", "Hermione", "Chandler", "Cady", "Barack", "Diana", "Heather", "Elle", "Ariel")) %>%
  filter(name %in% c("Christian", "Anastasia")) %>%
  filter(year>=2000) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = name)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = 2011),
             linetype = "dashed",
             color = "red") + 
    geom_vline(aes(xintercept = 2015),
             linetype = "dashed",
             color = "navy")
```

```{r}
babynames %>%
  #filter(name %in% c("Madison", "Hermione", "Chandler", "Cady", "Barack", "Diana", "Heather", "Elle", "Ariel")) %>%
  filter(name %in% c("Annakin", "Leia", "Luke", "Han")) %>%
  filter(year>=1950) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = 1977),
             linetype = "dashed",
             color = "red")
```

```{r}

babynames %>%
  #filter(name %in% c("Madison", "Hermione", "Chandler", "Cady", "Barack", "Diana", "Heather", "Elle", "Ariel")) %>%
  filter(name == "Madison") %>%
  #filter(year>=1960) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~sex, scales = "free_y")

mad_pre_splash <- babynames %>% 
  filter(name == "Madison", sex == "F", year < 1984) %>% 
  summarise(use = sum(n), avg = mean(n))

mad_pre_splash

mad_splash_to_90 <- babynames %>% 
  filter(name == "Madison", sex == "F", year >= 1984, year <1990) %>%
  group_by(year) %>% 
  summarise(use = sum(n))

mad_splash_to_90

mad_to_90_total <- 
  mad_splash_to_90 %>% 
  summarise(total = sum(use))

mad_to_90_total

mad_splash_to_present <- babynames %>% 
  filter(name == "Madison", sex == "F", year >= 1984)
  #group_by(year) 
  #summarise(use = sum(n))

mad_splash_to_present

avg_boys_mad_up_to_splash <- babynames %>% 
  filter(name == "Madison", sex=="M", year <1984) %>%
  summarise(avg = mean(n))

avg_boys_mad_postsplash <- babynames %>% 
  filter(name == "Madison", sex=="M", year >=1984) %>%
  summarise(avg = mean(n))
  
  
```


```{r}
babynames %>%
  filter(name %in% c("Indiana", "Marion")) %>%
  filter(year>=1980) %>% 
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y")
```
```{r}

#According to https://ohbabynames.com/all-baby-names/xander/, "Xander did not appear on the U.S. popularity charts as an independently given name until 1999"
babynames %>%
  #filter(name %in% c("Madison", "Hermione", "Chandler", "Cady", "Barack", "Diana", "Heather", "Elle", "Ariel")) %>%
  filter(name %in% c("Buffy", "Willow", "Xander", "Angel", "Drusilla")) %>%
  filter(year>=1960) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = 1997),
             linetype = "dashed",
             color = "red") +
  geom_vline(aes(xintercept = 2003),
             linetype = "dashed",
             color = "navy")
babynames %>% 
  filter(name=="Buffy")
  
```



```{r}
babynames %>%
  #filter(name %in% c("Madison", "Hermione", "Chandler", "Cady", "Barack", "Diana", "Heather", "Elle", "Ariel")) %>%
  filter(name %in% c("Drusilla")) %>%
  #filter(year>=1960) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = 1997),
             linetype = "dashed",
             color = "red") +
  geom_vline(aes(xintercept = 2003),
             linetype = "dashed",
             color = "navy")
```







```{r}

names <- c("Chandler", "Monica", "Ross", "Rachel", "Phoebe", "Joey", "Monica")
important_dates <- data.frame(
  name=names,
  year=c(1994, 1994, 1994, 1994, 1994, 1994, 1998)
)
babynames %>%
  #filter(name %in% c("Madison", "Hermione", "Chandler", "Cady", "Barack", "Diana", "Heather", "Elle", "Ariel")) %>%
  filter(name %in% names) %>%
  filter(year>=1980) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y") +
  geom_vline(aes(xintercept = year),
             linetype="dashed",
             color = "red",
             data = important_dates) 

#To make sure the right line is assigned to the right facet, make sure the vector for the line and for the plot are both "name", and then the faceting will apply to both , same for year
```


```{r}
names <-c("Chandler", "Monica", "Ross", "Rachel", "Phoebe", "Joey")
important_dates <- data.frame(
  name="Monica",
  year=1998
)

babynames %>% 
  filter(sex == "F", name == "Monica", year >1992, year < 2000)
babynames %>%
  filter(name %in% names) %>%
  filter(year>=1980) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  geom_vline(aes(xintercept = 1994),
             linetype = "dashed",
             color = "red") +
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept=year), linetype = "dashed", color = "navy", data = important_dates)

```


```{r}
babynames %>%
  filter(name %in% c("Kim", "Khloe", "Kris", "Kylie", "Kendall", "Kourtney")) %>%
  filter(year>=1980, sex == "F") %>% 
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = name)) + 
  facet_wrap(~name, scales = "free_y") +  geom_vline(aes(xintercept = 2007),
             linetype = "dashed",
             color = "red")

```
```{r}

babynames %>%
  filter(name %in% c("Chloe", "Khloe")) %>%
  filter(year>=1990, sex == "F") %>% 
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = name))


babynames %>%
  filter(name %in% c("Courtney", "Kourtney")) %>%
  filter(year>=1990, sex=="F") %>% 
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = name))

babynames %>%
  filter(name %in% c("Kris", "Chris")) %>%
  filter(year>=1990, sex=="F") %>% 
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = name))

babynames %>%
  filter(name %in% c("Kaitlin", "Caitlin", "Caitlyn", "Kaitlyn", "Catelyn", "Katelyn")) %>%
  filter(year>=1990, sex=="F") %>% 
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = name))

```
```{r}

kidsnames <- c("Mason", "Penelope", "Reign", "North", "Saint", "Dream")

kardashian_kids <- data.frame( 
  name = kidsnames, year = c(2009, 2012, 2014, 2013, 2015, 2016)
  
  )

babynames %>%
  filter(name %in% kidsnames) %>%
  filter(year>=2000) %>% 
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y") +  
  
    geom_vline(aes(xintercept = year),
             linetype = "dashed",
             color = "red",
             data = kardashian_kids)

```

```{r}
curry_names <- c("Ayesha", "Riley", "Ryan")

curry_family <- data.frame(
  
  name = curry_names, 
  year = c(2011, 2012, 2015)
  
)

babynames %>%
  filter(name %in% curry_names) %>%
  filter(year>=2000, sex=="F") %>% 
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = name)) + 
  facet_wrap(~name, scales = "free_y") +  
  
  geom_vline(aes(xintercept = year),
             linetype = "dashed",
             color = "red",
             data = curry_family)

```
```{r}

classic_tv_names <- c("Lucy", "Ethel", "Samantha", "Darren", "Andora", "Tabitha", "Donna", "Betty")

classic_tv <- data.frame(
  
  name = classic_tv_names,
  
  year = c(1951, 1951, 1964, 1964, 1964, 1966, 1958, 1921)
)

babynames %>%
  filter(name %in% c("Lucy", "Ethel", "Samantha", "Darren", "Andora", "Tabitha", "Donna", "Betty", "Wilma", "Judy")) %>%
  #filter(year>=1960) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = year),
             linetype = "dashed",
             color = "red",
             data = classic_tv)
  


```

```{r}
babynames %>%
  filter(name %in% c("Sasha", "Malia", "Michelle", "Barack")) %>%
  filter(year>=1990) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = 2008),
             linetype = "dashed",
             color = "red")

```

```{r}

babynames %>%
  filter(name %in% c("Meryl")) %>%
  filter(year>=1949) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = 1979),
             linetype = "dashed",
             color = "red")

```
```{r}
babynames %>%
  filter(name %in% c("Dustin")) %>%
  filter(year>=1949) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = 1967),
             linetype = "dashed",
             color = "navy") + 
    geom_vline(aes(xintercept = 1969),
             linetype = "dashed",
             color = "red") + 
    geom_vline(aes(xintercept = 1976),
             linetype = "dashed",
             color = "green") + 
    geom_vline(aes(xintercept = 1979),
             linetype = "dashed",
             color = "red")
```
```{r}
babynames %>%
  filter(name %in% c("Farrah", "Kate", "Jaclyn", "Charlie", "Sabrina", "Jill", "Kelly")) %>%
  filter(year>=1960) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y") + 
    geom_vline(aes(xintercept = 1976),
             linetype = "dashed",
             color = "navy")
  
```

```{r}

babynames %>%
  filter(name %in% c("Marilyn")) %>%
  filter(year>=1920) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = 1945),
             linetype = "dashed",
             color = "navy") + 
  geom_vline(aes(xintercept = 1962),
             linetype = "dashed",
             color = "navy")
  
  

```

```{r}
names60s <- c("Maggie", "Elizabeth","Elizabeth", "Julie", "Julie", "Barbra")

actresses60s <- data.frame(
  
  name = names60s, 
  
  year = c(1969, 1958, 1960, 1957, 1964, 1963)
  
)


babynames %>%
  filter(name %in% c("Maggie", "Elizabeth", "Julie", "Barbra")) %>%
  filter(year>=1940) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = year),
             linetype = "dashed",
             color = "red",
             data = actresses60s)
  

#1969, 1958, 1964, 1968

```


```{r}
babynames %>%
  filter(name %in% c("Rex", "Elton", "Fred")) %>%
  #filter(year>=1960) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y")
```

```{r}
babynames %>%
  filter(name %in% c("Audrey", "Grace")) %>%
  filter(year>=1930) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = 1953),
             linetype = "dashed",
             color = "navy")
  

#1953, 1956, 1954, 1943

```
```{r}
names40s <- c("Vivien", "Vivian", "Ginger", "Judy", "Katharine", "Katherine", "Ingrid")

actresses40s <- data.frame(
  
  name = names40s,
  
  year = c(1939, 1939, 1940, 1939, 1933, 1933, 1943)
)


babynames %>%
  filter(name %in% names40s) %>%
  filter(year>=1920, year <= 1965, sex=="F") %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = name)) + 
  facet_wrap(~name, scales = "free_y") + 
    geom_vline(aes(xintercept = year),
             linetype = "dashed",
             color = "red",
             data = actresses40s)

#1939, 1951, 1940, 1939, 1932, 1943
```
```{r}
babynames %>%
  filter(name %in% c("Reese", "Drew", "Demi", "Natalie", "Halle", "Halley", "Selena", "Miley" )) %>%
  filter(year>=1980) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y")

#Check Carrie Elsewhere
```
```{r}
babynames %>%
  filter(name %in% c("Serena", "Blair", "Blaire", "Blake", "Leighton","Lorelai", "Rory", "Penn" )) %>%
  filter(year>=1990) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y")
```
```{r}

babynames %>%
  filter(name %in% c("Finn", "Quinn", "Mercedes", "Kurt", "Santana")) %>%
  filter(year>=1990) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y")

```


