---
title: "names and pop culture"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown



```{r}
library(tidyverse)
```
```{r}
library(babynames)

```








```{r}
princess_names <- c("Ariel", "Belle", "Jasmine", "Mulan", "Tiana", "Merida", "Elsa", "Giselle")



princess_yrs <- data.frame(
  name = princess_names, 
  
  year = c(1989, 1991, 1992, 1998, 2009, 2012, 2013, 2007),
  
  release = c("Little Mermaid \n", "Beauty and \n the Beast \n", "Aladdin \n", "Mulan \n", "Princess and \n the Frog \n", "Brave \n", "Frozen \n", "Enchanted \n")
)


babynames %>%
  filter(name %in% princess_names, sex == "F") %>%
  filter(year>=1980) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = year, color = release),
             linetype="dashed",
             data = princess_yrs,
             size = 1) + 
  labs(title = "Disney Princesses", subtitle = "Vertical Line Marks Film's Release", y = "babies")

ggsave("disneyprincesses.png")
  
```







```{r}
babynames %>% 
  filter(name == "Belle", sex == "F", year >1980) %>% 
  ggplot() + 
  geom_point(mapping = aes(x = year, y = n))
```



```{r}
prince_names <- c("Eric", "Adam", "Aladdin", "Shang", "Naveen", "Kristoff", "Flynn") 

prince_yrs <- data.frame(
  name = prince_names, 
  
  year = c(1989, 1991, 1992, 1998, 2009, 2013, 2010),
  
  release = c("Little Mermaid \n", "Beauty and \n the Beast \n", "Aladdin \n", "Mulan \n", "Princess and \n the Frog \n", "Frozen \n", "Tangled \n")
  
  
)

babynames %>%
  filter(name %in% prince_names, sex == "M") %>%
  filter(year>=1980) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = year, color = release),
             linetype="dashed",
             size = 1,
             data = prince_yrs) + 
  labs(title = "Disney Princes", subtitle = "Vertical Line Marks Film's Release", y = "babies")

ggsave("disneyprinces.png")
```




```{r}

#year markers, introduction for Harry, ron, hermione, luna, minerva, and bellatrix. increasd involvement for ginny and neville, when he became good for severus


hp_names <- c("Harry", "Ron", "Hermione", "Neville", "Ginny", "Luna", "Minerva", "Bellatrix", "Severus", "Sirius", "Draco")

book_dates <- data.frame(
  name=hp_names, year = c(1997, 1997, 1997, 1997, 2003, 2003, 1997, 2003, 2007, 1999, 1997)
)

movie_dates <- data.frame(
  name=hp_names, year = c(2001, 2001, 2001, 2001, 2007, 2007, 2001, 2007, 2011, 2004, 2001)
)

babynames %>%
  filter(name %in% hp_names) %>%
  filter(year>=1990) %>%
  ggplot() +
  geom_point(mapping = aes( x = year, y = n, color = name)) + 
   geom_vline(aes(xintercept = year),
             linetype="dashed",
             color = "red",
             data = book_dates) +
   geom_vline(aes(xintercept = year),
             linetype="dashed",
             color = "navy",
             data = movie_dates) +
  facet_wrap(~name, scales = "free_y")
  
babynames %>%
  filter(name == "Bellatrix")
  

```

```{r}
#Book/Movie one

hp1_yrs <- data.frame(
  
  release = c("Book Release", "Movie Release"),
  
  yr = c(1997, 2001)
  
)

book1names <- c("Harry", "Ron", "Hermione", "Neville", "Minerva", "Draco")

babynames %>%
  filter(name %in% book1names) %>%
  filter(year>=1990) %>%
  ggplot() +
  geom_point(mapping = aes( x = year, y = n)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = yr, color = release),
             linetype="dashed",
             data = hp1_yrs, 
             size = 1) + 
  labs(title = "Harry Potter and the Sorcerer's Stone", subtitle = "Harry, Ron, Hermione, Neville, and Minerva McGonnagall are all introduced", y="babies")

ggsave("hp1.png")



```


```{r}
hp3_yrs <- data.frame(
  
  release = c("Book Release", "Movie Release"),
  
  yr = c(1999, 2004)
  
)

book3names <- c("Sirius")

babynames %>%
  filter(name %in% book3names) %>%
  filter(year>=1990) %>%
  ggplot() +
  geom_point(mapping = aes( x = year, y = n)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = yr, color = release),
             linetype="dashed",
             data = hp3_yrs, 
             size = 1) + 
  labs(title = "Harry Potter and the Prisoner of Azkaban", subtitle = "Sirius Black is introduced", y= "babies")
ggsave("hp3.png")



```

```{r}
hp5_yrs <- data.frame(
  
  release = c("Book Release", "Movie Release"),
  
  yr = c(2003, 2007)
  
)

book5names <- c("Ginny", "Bellatrix", "Luna")

babynames %>%
  filter(name %in% book5names) %>%
  filter(year>=1990) %>%
  ggplot() +
  geom_point(mapping = aes( x = year, y = n)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = yr, color = release),
             linetype="dashed",
             data = hp3_yrs, 
             size = 1) + 
  labs(title = "Harry Potter and the Order of the Phoenix", subtitle = "Luna and Bellatrix are introduced, Ginny takes on a prominent role", y = "babies")

ggsave("hp5.png")
```
```{r}

hp7_yrs <- data.frame(
  
  release = c("Book Release", "Movie Release"),
  
  yr = c(2007, 2011)
  
)

book7names <- c("Severus")

babynames %>%
  filter(name %in% book7names) %>%
  filter(year>=1990) %>%
  ggplot() +
  geom_point(mapping = aes( x = year, y = n)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = yr, color = release),
             linetype="dashed",
             data = hp7_yrs, 
             size = 1) + 
  labs(title = "Harry Potter and the Deathly Hallows", subtitle = "Severus Snape turns out to be good", y = "babies")

ggsave("hp7.png")

```

 

```{r}


babynames %>%
  #filter(name %in% c("Madison", "Hermione", "Chandler", "Cady", "Barack", "Diana", "Heather", "Elle", "Ariel")) %>%
  filter(name %in% c("Edward", "Esme", "Carlisle", "Emmett", "Alice", "Rosalie", "Jasper", "Bella")) %>%
  filter(year>=2000) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
   
  geom_vline(aes(xintercept = 2005),
             linetype = "dashed",
             color = "red", ) +
    geom_vline(aes(xintercept = 2008),
             linetype = "dashed",
             color = "navy",
             ) +
  #geom_text(x=2005, y = -Inf, label = "Book", size = 4, vjust = "bottom", hjust = "right") +
  
  #annotate("text", xmin = 2007, x = 2009, y = -Inf, label = "Movie", size = 4) +
  #annotate("text", x = 2004, xmax = 2006, y = -Inf, label = "Book", size = 4) +
  # coord_cartesian (clip = "off") + 
  # theme(panel.spacing = unit(1, "lines")) + 
  # geom_text(x=2005, y = -Inf, label = "Book", size = 4, y_nudge = -5) +
  facet_wrap(~name, scales = "free_y") + 
  labs(title = "Twilight Series", subtitle = "The first Twilight book was released in 2005; the first movie came out in 2008", y = "babies")

ggsave("twilight.png")

```
```{r}
babynames %>%
  #filter(name %in% c("Madison", "Hermione", "Chandler", "Cady", "Barack", "Diana", "Heather", "Elle", "Ariel")) %>%
  filter(name %in% c("Christian", "Anastasia")) %>%
  filter(year>=2000) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = name)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = 2011),
             linetype = "dashed",
             color = "red",
             size = 1) + 
    geom_vline(aes(xintercept = 2015),
             linetype = "dashed",
             color = "navy",
             size = 1) + 
  labs(title = "50 Shades of Gray", subtitle = "The first book came out in 2011; the first movie was released in 2015", y = "babies")

ggsave("50shades.png")
```



```{r}

babynames %>%
  #filter(name %in% c("Madison", "Hermione", "Chandler", "Cady", "Barack", "Diana", "Heather", "Elle", "Ariel")) %>%
  filter(name == "Madison", sex=="F") %>%
  #filter(year>=1960) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n)) +
  labs(title = "Girls Named Madison", subtitle = "Splash was released in 1983", y = "babies") +
    geom_vline(aes(xintercept = 1983),
             linetype = "dashed",
             color = "red",
             size = 1)
  ggsave("madisongirls.png")
  #facet_wrap(~sex, scales = "free_y")


babynames %>%
  #filter(name %in% c("Daryl")) %>%
  filter(name == "Madison", sex=="M") %>%
  #filter(year>=1960) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n)) +
    geom_vline(aes(xintercept = 1983),
             linetype = "dashed",
             color = "red",
             size = 1) + 
  labs(title = "Boys Named Madison", subtitle = "Splash was released in 1983", y = "babies")
ggsave("madisonboys.png")





mad_pre_splash <- babynames %>% 
  filter(name == "Madison", sex == "F", year < 1984) %>% 
  summarise(use = sum(n), avg = mean(n))

mad_pre_splash

mad_splash_to_90 <- babynames %>% 
  filter(name == "Madison", sex == "F", year >= 1984, year <1990) %>%
  group_by(year) %>% 
  summarise(use = sum(n))

mad_splash_to_90

mad_to_90_total <- 
  mad_splash_to_90 %>% 
  summarise(total = sum(use))

mad_to_90_total

mad_splash_to_present <- babynames %>% 
  filter(name == "Madison", sex == "F", year >= 1984)
  #group_by(year) 
  #summarise(use = sum(n))

mad_splash_to_present

avg_boys_mad_up_to_splash <- babynames %>% 
  filter(name == "Madison", sex=="M", year <1984) %>%
  summarise(avg = mean(n))

avg_boys_mad_postsplash <- babynames %>% 
  filter(name == "Madison", sex=="M", year >=1984) %>%
  summarise(avg = mean(n))
  
  
```


```{r}

#According to https://ohbabynames.com/all-baby-names/xander/, "Xander did not appear on the U.S. popularity charts as an independently given name until 1999"
babynames %>%
  filter(name %in% c("Buffy", "Willow", "Xander", "Angel", "Drusilla")) %>%
  filter(year>=1960) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = 1997),
             linetype = "dashed",
             color = "red", 
             size = 1) +
  geom_vline(aes(xintercept = 2003),
             linetype = "dashed",
             color = "navy", 
             size = 1) + 
  labs(title = "Buffy the Vampire Slayer", subtitle = "The show began airing in 1997 and ended 2003", y = "babies")
# babynames %>% 
#   filter(name=="Buffy")

ggsave("buffy.png")

  
```




```{r}

names <- c("Chandler", "Monica", "Ross", "Rachel", "Phoebe", "Joey", "Monica")
important_dates <- data.frame(
  name=names,
  year=c(1994, 1994, 1994, 1994, 1994, 1994, 1998),
  update= c("Friends First Airs","Friends First Airs", "Friends First Airs", "Friends First Airs","Friends First Airs", "Friends First Airs", "Scandal Breaks" )
)
babynames %>%
  filter(name %in% names) %>%
  filter(year>=1980) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, fill = sex), color = "black", stroke = 0.2, size = 1.5, shape = 21) + 
  facet_wrap(~name, scales = "free_y") +
  geom_vline(aes(xintercept = year, color = update),
             linetype="dashed",
             data = important_dates,
             size = 1) + 
  labs (title = "Friends", subtitle = "Friends began airing in 1994; the Lewinsky-Clinton Scandal broke in 1998", y = "babies")

ggsave("friends.png")

#To make sure the right line is assigned to the right facet, make sure the vector for the line and for the plot are both "name", and then the faceting will apply to both , same for year
```


```{r}
names <-c("Chandler", "Monica", "Ross", "Rachel", "Phoebe", "Joey")
important_dates <- data.frame(
  name="Monica",
  year=1998
)

babynames %>% 
  filter(sex == "F", name == "Monica", year >1992, year < 2000)
babynames %>%
  filter(name %in% names) %>%
  filter(year>=1980) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  geom_vline(aes(xintercept = 1994),
             linetype = "dashed",
             color = "red") +
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept=year), linetype = "dashed", color = "navy", data = important_dates)

```


```{r}
babynames %>%
  filter(name %in% c("Kim", "Khloe", "Kris", "Kylie", "Kendall", "Kourtney")) %>%
  filter(year>=1980, sex == "F") %>% 
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = name)) + 
  facet_wrap(~name, scales = "free_y") +  geom_vline(aes(xintercept = 2007),
             linetype = "dashed",
             color = "red",
             size = 1) + 
  labs(title = "Kardashian Family", subtitle = "Keeping Up with the Kardashians began airing in 2007", y = "babies")

ggsave("dash1stgen.png")

```
```{r}

babynames %>%
  filter(name %in% c("Chloe", "Khloe")) %>%
  filter(year>=1990, sex == "F") %>% 
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = name))


babynames %>%
  filter(name %in% c("Courtney", "Kourtney")) %>%
  filter(year>=1990, sex=="F") %>% 
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = name))

```
```{r}
kidsnames <- c("Mason", "Penelope", "Reign", "North", "Saint", "Dream")

kardashian_kids <- data.frame( 
  name = kidsnames, year = c(2009, 2012, 2014, 2013, 2015, 2016)
  
  )

babynames %>%
  filter(name %in% kidsnames) %>%
  filter(year>=2000) %>% 
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y") +  
  
    geom_vline(aes(xintercept = year),
             linetype = "dashed",
             color = "red",
             data = kardashian_kids,
             size = 1) + 
  labs(title = "Kardashian Children Born Before 2017", subtitle = "Vertical line denotes birth years", y = "babies")

ggsave("dash2ndgen.png")
```


```{r}
babynames %>% 
  filter(year==2011, sex == "M") %>% 
  arrange(desc(n))

babynames %>% 
  filter(year==2009, sex == "M") %>% 
  arrange(desc(n))
babynames %>% 
  filter(year==2010, sex == "M") %>% 
  arrange(desc(n))

```
```{r}
bewitched <- c("Samantha", "Darren", "Endora", "Tabitha")


babynames %>%
  filter(name %in% bewitched) %>%
  filter(year>=1940) %>%
  ggplot() +
  geom_point(mapping = aes( x=year, y = n, color = sex)) + 
  facet_wrap(~name, scales = "free_y") + 
  geom_vline(aes(xintercept = 1964),
             linetype = "dashed",
             color = "red",
             ) + 
  labs(title = "Bewitched", subtitle = "Bewitched began airing in 1964", y = "babies")

ggsave("bewitched.png")
```



